version: 2

sources:
  - name: raw_data
    database: calm-armor-443511-g8
    schema: cycle_dataset
    tables:
      - name: raw_cycle_data
        description: Raw cycling data for London, including trip counts by site, time, and conditions
        columns:
          - name: wave
            description: Survey wave or batch identifier
          - name: site_id
            description: Unique identifier for the cycling site
          - name: date
            description: Date of the cycling observation (in STRING format)
          - name: weather
            description: Weather conditions during the observation
          - name: time
            description: Time of the observation (in STRING format)
          - name: day
            description: Day of the week of the observation
          - name: round
            description: Observation round (e.g., morning, evening)
          - name: direction
            description: Direction of travel (e.g., inbound, outbound)
          - name: path
            description: Path type or distance metric (in FLOAT)
          - name: mode
            description: Mode of travel (e.g., bicycle, pedestrian)
          - name: count
            description: Number of trips or observations recorded
      - name: monitoring_locations
        description: Monitoring site metadata, including location and geographic details
        columns:
          - name: site_id
            description: Unique identifier for the monitoring site
          - name: location_description
            description: Description of the monitoring site location
          - name: borough
            description: Borough where the site is located
          - name: functional_area
            description: Functional area classification (e.g., 03 Outer)
          - name: road_type
            description: Type of road (integer code)
          - name: strategic_panel
            description: Strategic panel identifier (integer)
          - name: old_site_id
            description: Legacy site identifier
          - name: easting_uk_grid
            description: Easting coordinate in UK grid system
          - name: northing_uk_grid
            description: Northing coordinate in UK grid system
          - name: latitude
            description: Latitude of the site
          - name: longitude
            description: Longitude of the site

models:
  - name: stg_cycle_data
    description: Staging model for raw cycling data, with date and time combined into a timestamp
    columns:
      - name: wave
        description: The wave or season of the count (e.g., "2014 Q1 (Jan-Mar)")
      - name: site_id
        description: Unique ID for the monitoring location (e.g., "ML0001")
        tests:
          - not_null
      - name: date_time
        description: Timestamp of the count (e.g., "2014-01-24 06:00:00")
      - name: weather
        description: Weather conditions during the count (e.g., "Dry")
      - name: day
        description: Whether the count was on a weekday or weekend (e.g., "Weekday")
      - name: round
        description: Identifies repeated counts at the same location in the same wave (e.g., "A")
      - name: direction
        description: Direction of travel (e.g., "Northbound")
      - name: mode
        description: Type of road user counted (e.g., "Private cycles")
      - name: count
        description: Number of people counted in a 15-minute slot (e.g., 0, 15, 35)

  - name: stg_monitoring
    description: Staging model for monitoring locations, excluding geographic coordinates
    columns:
      - name: site_id
        description: Unique ID for each location (e.g., "ML1844")
        tests:
          - not_null
      - name: location_description
        description: Human-readable description of the place (e.g., "Wakering Road")
      - name: borough
        description: London borough where the site is located (e.g., "Barking & Dagenham")
      - name: functional_area
        description: Region classification Central, Inner, or Outer London (e.g., "03 Outer")
      - name: road_type
        description: Type of road (e.g., 0; integer code for A road, B road, etc.)
      - name: strategic_panel
        description: Flag (1 or 0) indicating if the site is part of TfL’s official panel
      - name: old_site_id
        description: Former ID of the site (e.g., "CFRCY014")
      - name: easting_uk_grid
        description: Easting coordinate in UK grid system (e.g., 544446.0)

  - name: fct_cycling_counts
    description: Fact table for cycling counts analytics, combining cycle data with monitoring site metadata
    columns:
      - name: record_id
        description: Unique surrogate key for each row (UUID)
        tests:
          - not_null
      - name: site_id
        description: Unique ID for the monitoring location (e.g., "ML0001")
        tests:
          - not_null
      - name: wave
        description: Wave or season of the count (e.g., "2014 Q1 (Jan-Mar)")
      - name: date_time
        description: Timestamp of the count (e.g., "2014-01-24 06:00:00")
        tests:
          - not_null
      - name: year
        description: Year extracted from date_time (e.g., 2014)
      - name: month
        description: Month extracted from date_time (e.g., 1)
      - name: day_of_week
        description: Day of week extracted from date_time (e.g., 6 for Friday)
      - name: hour
        description: Hour extracted from date_time (e.g., 6)
      - name: weather
        description: Weather conditions during the count (e.g., "Dry")
      - name: day
        description: Whether the count was on a weekday or weekend (e.g., "Weekday")
      - name: round
        description: Identifies repeated counts at the same location in the same wave (e.g., "A")
      - name: direction
        description: Direction of travel (e.g., "Northbound")
      - name: mode
        description: Type of road user counted (e.g., "Private cycles")
      - name: count
        description: Number of people counted in a 15-minute slot (e.g., 0, 15, 35)
      - name: location_description
        description: Human-readable description of the place (e.g., "Wakering Road")
      - name: borough
        description: London borough where the site is located (e.g., "Barking & Dagenham")
      - name: functional_area
        description: Region classification Central, Inner, or Outer London (e.g., "03 Outer")
      - name: road_type
        description: Type of road (e.g., 0; integer code for A road, B road Dijkstra, etc.)
      - name: strategic_panel
        description: Flag (1 or 0) indicating if the site is part of TfL’s official panel