
version: 2

sources:
  - name: staging
    database: calm-armor-443511-g8
    schema: cycle_dataset
      # loaded_at_field: record_loaded_at
    tables:
      - name: raw_cycle_data
        description: "The raw cycle data from the source system"
        columns:
          - name: wave
            description: "time period of the recorded data"
          - name: site_id
            description: "unique id of the cont location"
          - name: date
            description: "count date"
          - name: weather
            description: "Description of the weather at the time and location of the count."
          - name: time
            description: "The distance of the cycle in meters"
          - name: day
            description: "Indicates whether the count was done on a weekday or weekend."
          - name: round
            description: "Character indicating the iteration (‘round’) of the given count location"
          - name: direaction
            description: "The direction of the cycle"
          - name: path
            description: "Indicates the part of the road where the counts took place."
          - name: mode
            description: "Indicates the road user class being counted."
          - name: count
            description: "The count of the cycle"
# models:
#   - name: my_first_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         data_tests:
#           - unique
#           - not_null

#   - name: my_second_dbt_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         data_tests:
#           - unique
#           - not_null
